-- Carga de Profesores: IES Sierra de San Quílez (Binéfar)
DELETE FROM "Profesores";

INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, "grupo de guardia", rol, horas_guardia, activo)
VALUES
  ('prof_01', 'Abigail Lopez Ibarz', 'abigail.lopez@iesbinefar.es', 'Inglés', 'Profesorado', 'Docente', 1, true),
  ('prof_02', 'Ainara Mendoza', 'ainara.mendoza@iesbinefar.es', 'Orientación', 'Profesorado', 'Docente', 1, true),
  ('prof_03', 'Alba Maria Taboada Prieto', 'alba.taboada@iesbinefar.es', 'Lengua Castellana y Literatura', 'Profesorado', 'Docente', 1, true),
  ('prof_04', 'Alberto Galicia Albert', 'alberto.galicia@iesbinefar.es', 'Matemáticas', 'Profesorado', 'Docente', 1, true),
  ('prof_05', 'Alberto Ferraz Molina', 'alberto.ferraz@iesbinefar.es', 'Orientación', 'Profesorado', 'Docente', 1, true),
  ('prof_06', 'Ana Carrasquer Senar', 'ana.carrasquer@iesbinefar.es', 'Lengua Castellana y Literatura', 'Profesorado', 'Docente', 1, true),
  ('prof_07', 'Ana Torres Pere', 'ana.torres@iesbinefar.es', 'Inglés', 'Profesorado', 'Docente', 1, true),
  ('prof_08', 'Ana Maria Tornos Cullere', 'anamaria.tornos@iesbinefar.es', 'Música', 'Profesorado', 'Docente', 1, true),
  ('prof_09', 'Anabel Albero', 'anabel.albero@iesbinefar.es', 'Educación Física', 'Profesorado', 'Docente', 1, true),
  ('prof_10', 'Andrea Abenoza Mur', 'andrea.abenoza@iesbinefar.es', 'Inglés', 'Profesorado', 'Docente', 1, true),
  ('prof_11', 'Andrea Plata Gabas', 'andrea.plata@iesbinefar.es', 'Matemáticas', 'Profesorado', 'Docente', 1, true),
  ('prof_12', 'Anna Parras Martinez', 'anna.parras@iesbinefar.es', 'Lengua Castellana y Literatura', 'Profesorado', 'Docente', 1, true),
  ('prof_13', 'Antonio Diaz Merino', 'antonio.diaz@iesbinefar.es', 'Tecnología', 'Profesorado', 'Docente', 1, true),
  ('prof_14', 'Asier Gimeno Erburu', 'asier.gimeno@iesbinefar.es', 'IMA', 'Profesorado', 'Docente', 1, true),
  ('prof_15', 'Barbara Casas Floria', 'barbara.casas@iesbinefar.es', 'Inglés', 'Profesorado', 'Docente', 1, true),
  ('prof_16', 'Beatriz Salanova Ardanuy', 'beatriz.salanova@iesbinefar.es', 'Filosofía', 'Profesorado', 'Docente', 1, true),
  ('prof_17', 'Berenice Tierno Rios', 'berenice.tierno@iesbinefar.es', 'Francés', 'Profesorado', 'Docente', 1, true),
  ('prof_18', 'Bernardo Posa Cardiel', 'bernardo.posa@iesbinefar.es', 'Economía', 'Profesorado', 'Docente', 1, true),
  ('prof_19', 'Celia Alvarez Rodriguez', 'celia.alvarez@iesbinefar.es', 'Música', 'Profesorado', 'Docente', 1, true),
  ('prof_20', 'Cristina Santoveña Sanchez', 'cristina.santovena@iesbinefar.es', 'Peluquería', 'Profesorado', 'Docente', 1, true),
  ('prof_21', 'Cristina Piedrafita Claveria', 'cristina.piedrafita@iesbinefar.es', 'Tecnología', 'Profesorado', 'Docente', 1, true),
  ('prof_22', 'David Coma Folguera', 'david.coma@iesbinefar.es', 'Inglés', 'Profesorado', 'Docente', 1, true),
  ('prof_23', 'David Gimeno Clua', 'david.gimeno@iesbinefar.es', 'Orientación', 'Profesorado', 'Docente', 1, true),
  ('prof_24', 'Elias Lacasta Casterad', 'elias.lacasta@iesbinefar.es', 'Física y Química', 'Profesorado', 'Docente', 1, true),
  ('prof_25', 'Ester Polaina Lacambra', 'ester.polaina@iesbinefar.es', 'Biología y Geología', 'Profesorado', 'Docente', 1, true),
  ('prof_26', 'Francisco Javier Sandez Sieiro', 'franciscojavier.sandez@iesbinefar.es', 'Tecnología', 'Profesorado', 'Docente', 1, true),
  ('prof_27', 'Guillermo Jubero Garreta', 'guillermo.jubero@iesbinefar.es', 'Geografía e Historia', 'Profesorado', 'Docente', 1, true),
  ('prof_28', 'Ingrid Gruas', 'ingrid.gruas@iesbinefar.es', 'Geografía e Historia', 'Profesorado', 'Docente', 1, true),
  ('prof_29', 'Isabel Calvillo Olmedo', 'isabel.calvillo@iesbinefar.es', 'Inglés', 'Profesorado', 'Docente', 1, true),
  ('prof_30', 'Isabel Sese Monclus', 'isabel.sese@iesbinefar.es', 'Matemáticas', 'Profesorado', 'Docente', 1, true),
  ('prof_31', 'Isabel Ruiz Cerrillo', 'isabel.ruiz@iesbinefar.es', 'Latín y Griego', 'Profesorado', 'Docente', 1, true),
  ('prof_32', 'Jason Bautista Vera', 'jason.bautista@iesbinefar.es', 'Filosofía', 'Profesorado', 'Docente', 1, true),
  ('prof_33', 'Javier Chine Mestres', 'javier.chine@iesbinefar.es', 'IMA', 'Profesorado', 'Docente', 1, true),
  ('prof_34', 'Javier Cristobal', 'javier.cristobal@iesbinefar.es', 'IMA', 'Profesorado', 'Docente', 1, true),
  ('prof_35', 'Jenny Martinez Adell', 'jenny.martinez@iesbinefar.es', 'Peluquería', 'Profesorado', 'Docente', 1, true),
  ('prof_36', 'Jose Agustin Aldaz Goni', 'joseagustin.aldaz@iesbinefar.es', 'Matemáticas', 'Profesorado', 'Docente', 1, true),
  ('prof_37', 'Jose Antonio Oliva Martin', 'joseantonio.oliva@iesbinefar.es', 'Orientación', 'Profesorado', 'Docente', 1, true),
  ('prof_38', 'Jose Emilio Castillon Solano', 'joseemilio.castillon@iesbinefar.es', 'Tecnología', 'Profesorado', 'Docente', 1, true),
  ('prof_39', 'José Luis Ibañez Pons', 'joseluis.ibanez@iesbinefar.es', 'Matemáticas', 'Profesorado', 'Docente', 1, true),
  ('prof_40', 'José Manuel Gorjon Sanz', 'josemanuel.gorjon@iesbinefar.es', 'Educación Física', 'Profesorado', 'Docente', 1, true),
  ('prof_41', 'Juan de la Cruz Irazabal Villar', 'juandelacruz.irazabal@iesbinefar.es', 'Educación Plástica', 'Profesorado', 'Docente', 1, true),
  ('prof_42', 'Julia Barrio Ruiz de Viñaspre', 'julia.barrio@iesbinefar.es', 'IMA', 'Profesorado', 'Docente', 1, true),
  ('prof_43', 'Laura Vilalta Rodellar', 'laura.vilalta@iesbinefar.es', 'FOL', 'Profesorado', 'Docente', 1, true),
  ('prof_44', 'Lidia Borruel Mairal', 'lidia.borruel@iesbinefar.es', 'Educación Física', 'Profesorado', 'Docente', 1, true),
  ('prof_45', 'Lourdes Carrasquer', 'lourdes.carrasquer@iesbinefar.es', 'Educación Física', 'Profesorado', 'Docente', 1, true),
  ('prof_46', 'Lourdes Sanchez de los Santos', 'lourdes.sanchez@iesbinefar.es', 'Educación Física', 'Profesorado', 'Docente', 1, true),
  ('prof_47', 'Lucia Oliva', 'lucia.oliva@iesbinefar.es', 'Peluquería', 'Profesorado', 'Docente', 1, true),
  ('prof_48', 'Lucia Gracia Salazar', 'lucia.graciasalazar@iesbinefar.es', 'Educación Plástica', 'Profesorado', 'Docente', 1, true),
  ('prof_49', 'Luis Orus Calvet', 'luis.orus@iesbinefar.es', 'Música', 'Profesorado', 'Docente', 1, true),
  ('prof_50', 'Luis Miguel Clemente Aljaro', 'luismi.clemente@iesbinefar.es', 'Lengua Castellana y Literatura', 'Profesorado', 'Docente', 1, true),
  ('prof_51', 'Manuel Buil Trigo', 'manuel.buil@iesbinefar.es', 'Biología y Geología', 'Profesorado', 'Docente', 1, true),
  ('prof_52', 'Maria Dueso', 'maria.dueso@iesbinefar.es', 'Orientación', 'Profesorado', 'Docente', 1, true),
  ('prof_53', 'Maria Carmen Tornos Mola', 'mariacarmen.tornos@iesbinefar.es', 'Geografía e Historia', 'Profesorado', 'Docente', 1, true),
  ('prof_54', 'Maria Dolores Vazquez Miranda', 'mariadolores.vazquez@iesbinefar.es', 'Lengua Castellana y Literatura', 'Profesorado', 'Docente', 1, true),
  ('prof_55', 'Maria Dolores Raso Escur', 'mariadolores.raso@iesbinefar.es', 'Inglés', 'Profesorado', 'Docente', 1, true),
  ('prof_56', 'Maria Jesus Garces Ramos', 'mariajesus.garces@iesbinefar.es', 'Geografía e Historia', 'Profesorado', 'Docente', 1, true),
  ('prof_57', 'Maria Jose Paniello Alastruey', 'mariajose.paniello@iesbinefar.es', 'Física y Química', 'Profesorado', 'Docente', 1, true),
  ('prof_58', 'Marina Sopesens Vinos', 'marina.sopesens@iesbinefar.es', 'Francés', 'Profesorado', 'Docente', 1, true),
  ('prof_59', 'Marta Ibarz', 'marta.ibarz@iesbinefar.es', 'Lengua Castellana y Literatura', 'Profesorado', 'Docente', 1, true),
  ('prof_60', 'María del Pilar Miguel Casanova', 'mariadelpilar.miguel@iesbinefar.es', 'Lengua Castellana y Literatura', 'Profesorado', 'Docente', 1, true),
  ('prof_61', 'Miguel Angel Gomez Saso', 'miguelangel.gomez@iesbinefar.es', 'Física y Química', 'Profesorado', 'Docente', 1, true),
  ('prof_62', 'Montserrat Bañeres Farrero', 'montserrat.baneres@iesbinefar.es', 'Tecnología', 'Profesorado', 'Docente', 1, true),
  ('prof_63', 'Montserrat Martinez Cordero', 'montserrat.martinez@iesbinefar.es', 'Religión', 'Profesorado', 'Docente', 1, true),
  ('prof_64', 'Natalia Carrera', 'natalia.carrera@iesbinefar.es', 'Orientación', 'Profesorado', 'Docente', 1, true),
  ('prof_65', 'Pablo Rodrigo Cardona', 'pablo.rodrigo@iesbinefar.es', 'Inglés', 'Profesorado', 'Docente', 1, true),
  ('prof_66', 'Patricia Salamero Aguayos', 'patricia.salamero@iesbinefar.es', 'Orientación', 'Profesorado', 'Docente', 1, true),
  ('prof_67', 'Raquel Prats Avilla', 'raquel.prats@iesbinefar.es', 'Educación Plástica', 'Profesorado', 'Docente', 1, true),
  ('prof_68', 'Raquel Garcia Perales', 'raquel.garcia@iesbinefar.es', 'Lengua Castellana y Literatura', 'Profesorado', 'Docente', 1, true),
  ('prof_69', 'Raquel Abadias Ibarbia', 'raquel.abadias@iesbinefar.es', 'Física y Química', 'Profesorado', 'Docente', 1, true),
  ('prof_70', 'Roi Silva Casal', 'roi.silva@iesbinefar.es', 'Biología y Geología', 'Profesorado', 'Docente', 1, true),
  ('prof_71', 'Samuel Cester Aguirre', 'samuel.cester@iesbinefar.es', 'Economía', 'Profesorado', 'Docente', 1, true),
  ('prof_72', 'Samuel Garcia Lasheras', 'samuel.garcia@iesbinefar.es', 'Geografía e Historia', 'Profesorado', 'Docente', 1, true),
  ('prof_73', 'Sandhya Carmona Ogalla', 'sandhya.carmona@iesbinefar.es', 'Lengua Castellana y Literatura', 'Profesorado', 'Docente', 1, true),
  ('prof_74', 'Sandra Espada Senar', 'sandra.espada@iesbinefar.es', 'Orientación', 'Profesorado', 'Docente', 1, true),
  ('prof_75', 'Sandra Claver Romeo', 'sandra.claver@iesbinefar.es', 'Biología y Geología', 'Profesorado', 'Docente', 1, true),
  ('prof_76', 'Santiago Felez Moliner', 'santiago.felez@iesbinefar.es', 'Matemáticas', 'Profesorado', 'Docente', 1, true),
  ('prof_77', 'Santiago Martin Ulecia', 'santiago.martin@iesbinefar.es', 'Religión', 'Profesorado', 'Docente', 1, true),
  ('prof_78', 'Sergio Blazquez', 'sergio.blazquez@iesbinefar.es', 'IMA', 'Profesorado', 'Docente', 1, true),
  ('prof_79', 'Teresa Bernues Alcolea', 'teresa.bernues@iesbinefar.es', 'Geografía e Historia', 'Profesorado', 'Docente', 1, true),
  ('prof_80', 'Yolanda Salas Herbera', 'yolanda.salas@iesbinefar.es', 'Matemáticas', 'Profesorado', 'Docente', 1, true),
  ('prof_81', 'Yolanda Marias Ferrer', 'yolanda.marias@iesbinefar.es', 'Matemáticas', 'Equipo Directivo', 'Jefatura', 1, true),
  ('prof_82', 'Rocio Guarné Chaverri', 'rocio.guarne@iesbinefar.es', 'Lengua Castellana y Literatura', 'Equipo Directivo', 'Jefatura', 1, true),
  ('prof_83', 'Sara Samitier Boix', 'sara.samitier@iesbinefar.es', 'Lengua Castellana y Literatura', 'Equipo Directivo', 'Jefatura', 1, true),
  ('prof_84', 'Susana Sanz Moros', 'susana.sanz@iesbinefar.es', 'Tecnología', 'Equipo Directivo', 'Jefatura', 1, true),
  ('prof_85', 'José Ramón Barrabés Campo', 'joseramon.barrabes@iesbinefar.es', 'IMA', 'Equipo Directivo', 'Jefatura', 1, true),
  ('prof_86', 'Araceli Muñoz Jiménez', 'araceli.munoz@iesbinefar.es', 'Matemáticas', 'Profesorado', 'Docente', 1, true),
  ('prof_87', 'Juan José Nieto Callén', 'juanjose.nieto@iesbinefar.es', 'Geografía e Historia', 'Profesorado', 'Docente', 1, true),
  ('prof_88', 'Samuel Villabrille Naharro', 'samuel.villabrille@iesbinefar.es', 'API', 'Profesorado', 'Docente', 1, true),
  ('prof_89', 'Jorge Calvo Martín', 'jorge.calvo@iesbinefar.es', 'Física y Química', 'Profesorado', 'Docente', 1, true),
  ('prof_90', 'Rosabel Sancho Lostal', 'rosabel.sancho@iesbinefar.es', 'Peluquería', 'Profesorado', 'Docente', 1, true);
