BEGIN;
TRUNCATE TABLE "Activity_Logs" CASCADE;
TRUNCATE TABLE "Guardias" CASCADE;
TRUNCATE TABLE "Horario_Personal" CASCADE;
TRUNCATE TABLE "Grupos_Guardia" CASCADE;
TRUNCATE TABLE "Cuadrante_Guardias" CASCADE;
DELETE FROM "Profesores" WHERE "email" <> 'alplanast@iesreyescatolicos.com';
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P002', 'Natalia Campo Monclus', 'nacampom@iesreyescatolicos.com', 'AGRARIAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P003', 'Javier Bernal Garcés', 'jabernalg@iesreyescatolicos.com', 'AGRARIAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P004', 'Carlos Fernández Mélida', 'cafernandezm@iesreyescatolicos.com', 'AGRARIAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P005', 'René Mozo Martín', 'remozom@iesreyescatolicos.com', 'AGRARIAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P006', 'Laura Vicente Torres', 'lavicentet@iesreyescatolicos.com', 'AGRARIAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P007', 'Carlos Yera Solana', 'cayeras@iesreyescatolicos.com', 'AGRARIAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P008', 'Mª Pilar Longas Acín', 'mplongasa@iesreyescatolicos.com', 'ARTES PLÁSTICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P009', 'Laura Soriano Marco', 'lasorianom@iesreyescatolicos.com', 'ARTES PLÁSTICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P010', 'Francisco Elizalde Lasheras', 'frelizaldel@iesreyescatolicos.com', 'BIOLOGÍA Y GEOLOGÍA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P011', 'Javier Gutierrez Fernández', 'jagutierrezf@iesreyescatolicos.com', 'BIOLOGÍA Y GEOLOGÍA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P012', 'Teresa Naudín Ayesa', 'tenaudina@iesreyescatolicos.com', 'BIOLOGÍA Y GEOLOGÍA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P013', 'Marisa Ruiz Asensio', 'maruiza@iesreyescatolicos.com', 'BIOLOGÍA Y GEOLOGÍA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P014', 'Irene Villa Orduna', 'irvillao@iesreyescatolicos.com', 'BIOLOGÍA Y GEOLOGÍA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P015', 'Sandra Villa Navarro', 'savillan@iesreyescatolicos.com', 'ECONOMÍA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P016', 'Antonio Gallego Hernández', 'angallegoh@iesreyescatolicos.com', 'ECONOMÍA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P017', 'Gonzalo Mondéjar Martín', 'gomondejarm@iesreyescatolicos.com', 'EDUCACIÓN FÍSICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P018', 'David Boudet Azcárate', 'daboudeta@iesreyescatolicos.com', 'EDUCACIÓN FÍSICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P019', 'Miguel Ángel Moreno Navascués', 'mamorenon@iesreyescatolicos.com', 'EDUCACIÓN FÍSICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P020', 'Tomás Puente Giménez', 'topuenteg@iesreyescatolicos.com', 'EDUCACIÓN FÍSICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P021', 'Óscar Rodrigo Murillo', 'osrodrigom@iesreyescatolicos.com', 'EDUCACIÓN FÍSICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P022', 'Pablo Benedé Júlvez', 'pabenedej@iesreyescatolicos.com', 'EDUCACIÓN FÍSICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P023', 'Anabel Martínez Hernández', 'aimartinezh@iesreyescatolicos.com', 'FILOSOFÍA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P024', 'Mª del Carmen Beltrán Senao', 'mcbeltrans@iesreyescatolicos.com', 'FILOSOFÍA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P025', 'Julia Sabalza Montañés', 'jusabalzam@iesreyescatolicos.com', 'FOL', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P026', 'Ana Millana Fañanás', 'anmillanaf@iesreyescatolicos.com', 'FRANCÉS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P027', 'Sara Fuertes Soler', 'safuertess@iesreyescatolicos.com', 'FRANCÉS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P028', 'María Gállego Blasco', 'magallegob@iesreyescatolicos.com', 'FRANCÉS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P029', 'Jesús Marco Conde', 'jemarcoc@iesreyescatolicos.com', 'FRANCÉS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P030', 'Andrés Membrado Royo', 'anmembrador@iesreyescatolicos.com', 'FÍSICA Y QUÍMICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P031', 'Laura Blas Aguerri', 'lablasa@iesreyescatolicos.com', 'FÍSICA Y QUÍMICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P032', 'Raquel Sagrario Sanz Lacosta', 'rssanzl@iesreyescatolicos.com', 'FÍSICA Y QUÍMICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P033', 'Antonio Lacosta Aragüés', 'ajlacostaa@iesreyescatolicos.com', 'GEOGRAFÍA E HISTORIA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P034', 'Silvia Escañuela Barradas', 'siescanuelab@iesreyescatolicos.com', 'GEOGRAFÍA E HISTORIA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P035', 'Jaime Nuño Martínez', 'janunom@iesreyescatolicos.com', 'GEOGRAFÍA E HISTORIA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P036', 'Paloma Prádanos Herrera', 'papradanosh@iesreyescatolicos.com', 'GEOGRAFÍA E HISTORIA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P037', 'Diana Sancho Malón', 'disanchom@iesreyescatolicos.com', 'GEOGRAFÍA E HISTORIA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P038', 'Marina Senero Sauras', 'maseneros@iesreyescatolicos.com', 'INGLÉS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P039', 'Inés Pilar Giménez Urdániz', 'ipgimenezu@iesreyescatolicos.com', 'INGLÉS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P040', 'Silvia Guajardo Aragüés', 'siguajardoa@iesreyescatolicos.com', 'INGLÉS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P041', 'Eva Luna Cardiel', 'evlunac@iesreyescatolicos.com', 'INGLÉS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P042', 'Silvia Mañero Hernández', 'simaneroh@iesreyescatolicos.com', 'INGLÉS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P043', 'Virginia Monforte Román', 'vimonforter@iesreyescatolicos.com', 'INGLÉS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P044', 'Patricia Ponce Pérez', 'paponcep@iesreyescatolicos.com', 'INGLÉS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P045', 'Adriana Potrony Ciudad', 'adpotronyc@iesreyescatolicos.com', 'INGLÉS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P046', 'Antonio Royo', 'anroyol@iesreyescatolicos.com', 'LATÍN Y GRIEGO', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P047', 'Vanesa Cueto Viñau', 'vacuetov@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P048', 'Patxi Abadía Álvarez', 'paabadiaa@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P049', 'Tatiana Eusebio Ruiz Esquide', 'taeusebior@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P050', 'Sara Jaso Pérez', 'sajasop@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P051', 'Dario Navarro Peguero', 'danavarrop@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P052', 'Javier Maldonado Fernández', 'jamaldonadof@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P053', 'Mª José Miranda Romero', 'mjmirandar@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P054', 'Daniel Rodriguez Anaya', 'darodrigueza@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P055', 'María Rubio Torres', 'marubiot@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P056', 'Ana Belén Caraballo', 'abcaraballot@iesreyescatolicos.com', 'MATEMÁTICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P057', 'Primitiva Alcusón Puyuelo', 'pralcusonp@iesreyescatolicos.com', 'MATEMÁTICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P058', 'Francisco Javier García Pardos', 'fjgarciap@iesreyescatolicos.com', 'MATEMÁTICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P059', 'Ángel Gumiel Correo', 'angumielc@iesreyescatolicos.com', 'MATEMÁTICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P060', 'José María Lorenzo Martínez', 'jmlorenzom@iesreyescatolicos.com', 'MATEMÁTICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P061', 'Ana Palma Cobo', 'anpalmac@iesreyescatolicos.com', 'MATEMÁTICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P062', 'Paula Villuendas Calvete', 'pavilluendasc@iesreyescatolicos.com', 'MATEMÁTICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P063', 'José María Moreno Loscertales', 'jmmorenol@iesreyescatolicos.com', 'MATEMÁTICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P064', 'Mª Esther Arilla Luna', 'mearillal@iesreyescatolicos.com', 'MÚSICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P065', 'Daniel Giménez Pérez', 'dagimenezp@iesreyescatolicos.com', 'MÚSICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P066', 'Idoia Mena Ederra', 'idmenae@iesreyescatolicos.com', 'MÚSICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P067', 'María Ruíz Chueca', 'maruizc@iesreyescatolicos.com', 'ORIENTACIÓN', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P068', 'Mª Cruz Aznárez Maiza', 'mcaznarezm@iesreyescatolicos.com', 'ORIENTACIÓN', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P069', 'Begoña Montañés Aragüés', 'bemontanesa@iesreyescatolicos.com', 'ORIENTACIÓN', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P070', 'Rosana Valenzuela Fuertes', 'rnvalenzuelaf@iesreyescatolicos.com', 'ORIENTACIÓN', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P071', 'Víctor Pola Aznar', 'vmpolaa@iesreyescatolicos.com', 'RELIGIÓN', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P072', 'Beatriz Izuel Montañés', 'beizuelm@iesreyescatolicos.com', 'SERVICIOS A LA COMUNIDAD', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P073', 'María del Pilar Aparicio Aguerri', 'mpaparicioa@iesreyescatolicos.com', 'SERVICIOS A LA COMUNIDAD', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P074', 'Miriam Buj Ibáñez', 'mibuji@iesreyescatolicos.com', 'SERVICIOS A LA COMUNIDAD', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P075', 'Agustín Burillo Tomás', 'agburillot@iesreyescatolicos.com', 'SERVICIOS A LA COMUNIDAD', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P076', 'Diana Gracia Villarrolla', 'digraciav@iesreyescatolicos.com', 'SERVICIOS A LA COMUNIDAD', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P077', 'Macarena Santa-Maria Megia', 'masantamariam@iesreyescatolicos.com', 'SERVICIOS A LA COMUNIDAD', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P078', 'Alejandro Yeste Iglesias', 'alyestei@iesreyescatolicos.com', 'PROCEDIMIENTOS SANITARIOS Y ASISTENCIALES', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P079', 'Virginia Benavente Monguilod', 'vibenaventem@iesreyescatolicos.com', 'TECNOLOGÍA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P080', 'Ana María Sánchez Jarque', 'amsanchezj@iesreyescatolicos.com', 'TECNOLOGÍA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P081', 'Carolina Romero Beguería', 'caromerob@iesreyescatolicos.com', 'TECNOLOGÍA', 'Usuario', 1);
COMMIT;