-- ====================================================================
-- SCRIPT DE INICIALIZACIÓN COMPLETO: IES PEDRO DE LUNA (ZARAGOZA)
-- ====================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

BEGIN;

-- 1. Tipo de Datos de Usuarios
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Tipos de usuarios') THEN
        CREATE TYPE "Tipos de usuarios" AS ENUM ('superadmin', 'Administrador', 'Admin', 'Jefatura', 'Administración', 'Docente', 'Usuario', 'Pantalla');
    END IF;
END $$;

-- 2. Creación de Tablas Principales

CREATE TABLE IF NOT EXISTS public."Profesores" (
    id text PRIMARY KEY,
    "nombre y apellidos" text NOT NULL,
    email text UNIQUE,
    departamento text,
    "grupo de guardia" text,
    foto text,
    avatar_seed text,
    rol text DEFAULT 'Usuario',
    user_id uuid,
    horas_guardia integer DEFAULT 1,
    activo boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS public."Franjas horarias" (
    "id franja" text PRIMARY KEY,
    franja text,
    "hora inicio" text,
    "hora fin" text,
    tipo text
);

CREATE TABLE IF NOT EXISTS public."Aulas" (
    "id aulas" text PRIMARY KEY,
    aulas text UNIQUE NOT NULL,
    edificio text,
    ubicacion text
);

CREATE TABLE IF NOT EXISTS public."Materias" (
    "id materias" text PRIMARY KEY,
    materias text UNIQUE NOT NULL,
    padre_id text
);

CREATE TABLE IF NOT EXISTS public."Grupos" (
    "id grupos" text PRIMARY KEY,
    grupos text UNIQUE NOT NULL,
    tutor_id text REFERENCES public."Profesores"(id) ON DELETE SET NULL,
    nivel text,
    aula_habitual text
);

CREATE TABLE IF NOT EXISTS public."Grupos_Guardia" (
    id text PRIMARY KEY,
    nombre text NOT NULL,
    profesores_asignados jsonb DEFAULT '[]'::jsonb,
    color text,
    "orden_rotación" integer,
    activo boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS public."Horario_Personal" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesor_id text REFERENCES public."Profesores"(id) ON DELETE CASCADE,
    "día" integer NOT NULL,
    tramo_horario text REFERENCES public."Franjas horarias"("id franja") ON DELETE CASCADE,
    asignatura text,
    grupo text,
    aula text,
    es_guardia boolean DEFAULT false,
    tipo_guardia text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."Guardias" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "profesor que falta" text REFERENCES public."Profesores"(id) ON DELETE SET NULL,
    fecha date NOT NULL,
    horario text REFERENCES public."Franjas horarias"("id franja") ON DELETE RESTRICT,
    "aula de guardia" text,
    "grupo de alumnos" text,
    "profesor de guardia" text REFERENCES public."Profesores"(id) ON DELETE SET NULL,
    "tipo de guardia" text,
    estado text DEFAULT 'Pendiente',
    motivo text,
    observaciones text,
    tarea text,
    firma_confirmacion text,
    "hora de firma" timestamp with time zone,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."Activity_Logs" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid,
    user_email text,
    user_name text,
    action text NOT NULL,
    entity_type text,
    entity_id text,
    details jsonb,
    ip_address text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."reservas_aulas" (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    aula_id text REFERENCES public."Aulas"("id aulas") ON DELETE CASCADE,
    profesor_id text REFERENCES public."Profesores"(id) ON DELETE CASCADE,
    fecha date NOT NULL,
    tramo_horario text REFERENCES public."Franjas horarias"("id franja") ON DELETE CASCADE,
    motivo text,
    anual boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."libre_disposicion" (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    profesor_id text REFERENCES public."Profesores"(id) ON DELETE CASCADE,
    fecha date NOT NULL,
    motivo text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public."configuracion_centro" (
    id integer PRIMARY KEY,
    nombre_centro text,
    direccion_centro text,
    telefono_centro text,
    email_centro text,
    logo_url text
);

-- Tabla: Calendario
CREATE TABLE IF NOT EXISTS public."Calendario" (
    "id" BIGSERIAL PRIMARY KEY,
    "fecha" DATE UNIQUE NOT NULL,
    "es_lectivo" BOOLEAN NOT NULL DEFAULT true,
    "descripcion" TEXT,
    "created_at" TIMESTAMPTZ DEFAULT NOW()
);

-- Tabla: calendar_events
CREATE TABLE IF NOT EXISTS public.calendar_events (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    date DATE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Habilitar RLS en todas las tablas
ALTER TABLE public."Profesores" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Franjas horarias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Aulas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Materias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Grupos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Grupos_Guardia" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Horario_Personal" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Guardias" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Activity_Logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."reservas_aulas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."libre_disposicion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."configuracion_centro" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Calendario" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.calendar_events ENABLE ROW LEVEL SECURITY;

-- 4. Crear Políticas RLS
DO $$ 
DECLARE
    tbl text;
BEGIN
    FOR tbl IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' 
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Permitir lectura para todos" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Permitir lectura para todos" ON public.%I FOR SELECT USING (true)', tbl);
        EXECUTE format('DROP POLICY IF EXISTS "Permitir escritura para todos" ON public.%I', tbl);
        EXECUTE format('CREATE POLICY "Permitir escritura para todos" ON public.%I FOR ALL USING (true)', tbl);
    END LOOP;
END $$;

-- 5. Insertar Cuenta Administrador Inicial para IES Pedro de Luna
DELETE FROM public."Profesores";
INSERT INTO public."Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia, activo) 
VALUES ('P001', 'Alberto Planas / Jefatura', 'guardias@iespedrodeluna.es', 'EQUIPO DIRECTIVO', 'Admin', 1, true);

-- Configuración del Centro
INSERT INTO public."configuracion_centro" (id, nombre_centro, direccion_centro, email_centro)
VALUES (1, 'IES Pedro de Luna', 'Calle Universidad, 2, 50001 Zaragoza', 'guardias@iespedrodeluna.es')
ON CONFLICT (id) DO UPDATE SET 
    nombre_centro = EXCLUDED.nombre_centro,
    direccion_centro = EXCLUDED.direccion_centro,
    email_centro = EXCLUDED.email_centro;

-- 6. Población automática del Calendario Escolar Oficial Aragón 2026-2027
TRUNCATE TABLE public."Calendario" CASCADE;
INSERT INTO public."Calendario" ("fecha", "es_lectivo", "descripcion")
SELECT 
    d::date AS fecha,
    CASE 
        WHEN EXTRACT(DOW FROM d) IN (0, 6) THEN false
        WHEN d::date = '2026-10-12' THEN false
        WHEN d::date = '2026-11-02' THEN false
        WHEN d::date = '2026-12-07' THEN false
        WHEN d::date = '2026-12-08' THEN false
        WHEN d::date BETWEEN '2026-12-23' AND '2027-01-06' THEN false
        WHEN d::date IN ('2027-02-18', '2027-02-19') THEN false
        WHEN d::date BETWEEN '2027-03-25' AND '2027-04-02' THEN false
        WHEN d::date = '2027-04-23' THEN false
        WHEN d::date = '2027-05-01' THEN false
        WHEN d::date = '2027-05-03' THEN false
        WHEN d::date < '2026-09-08' THEN false
        WHEN d::date > '2027-06-18' THEN false
        ELSE true
    END AS es_lectivo,
    CASE 
        WHEN EXTRACT(DOW FROM d) IN (0, 6) THEN 'Fin de semana'
        WHEN d::date = '2026-10-12' THEN 'Fiesta Nacional de España / El Pilar'
        WHEN d::date = '2026-11-02' THEN 'Lunes siguiente a Todos los Santos'
        WHEN d::date = '2026-12-07' THEN 'Puente de la Constitución'
        WHEN d::date = '2026-12-08' THEN 'Inmaculada Concepción'
        WHEN d::date BETWEEN '2026-12-23' AND '2027-01-06' THEN 'Vacaciones de Navidad'
        WHEN d::date IN ('2027-02-18', '2027-02-19') THEN 'Día no lectivo provincial (Carnaval)'
        WHEN d::date BETWEEN '2027-03-25' AND '2027-04-02' THEN 'Vacaciones de Semana Santa'
        WHEN d::date = '2027-04-23' THEN 'Día de Aragón (San Jorge)'
        WHEN d::date = '2027-05-01' THEN 'Fiesta del Trabajo'
        WHEN d::date = '2027-05-03' THEN 'Día no lectivo provincial (Zaragoza)'
        WHEN d::date < '2026-09-08' THEN 'Inicio de curso profesorado / Preparación'
        WHEN d::date > '2027-06-18' THEN 'Evaluaciones y trámites fin de curso'
        ELSE NULL
    END AS descripcion
FROM generate_series('2026-09-01'::date, '2027-06-30'::date, '1 day'::interval) d;

COMMIT;
