BEGIN;
TRUNCATE TABLE "Activity_Logs" CASCADE;
TRUNCATE TABLE "Guardias" CASCADE;
TRUNCATE TABLE "Horario_Personal" CASCADE;
TRUNCATE TABLE "Grupos_Guardia" CASCADE;
TRUNCATE TABLE "Cuadrante_Guardias" CASCADE;
DELETE FROM "Profesores" WHERE "email" <> 'alplanast@iesreyescatolicos.com';
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P002', 'Natalia Campo Monclus', 'nacampom@iesreyescatolicos.com', 'AGRARIAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P003', 'Javier Bernal GarcÚs', 'jabernalg@iesreyescatolicos.com', 'AGRARIAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P004', 'Carlos Fernßndez MÚlida', 'cafernandezm@iesreyescatolicos.com', 'AGRARIAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P005', 'RenÚ Mozo MartÝn', 'remozom@iesreyescatolicos.com', 'AGRARIAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P006', 'Laura Vicente Torres', 'lavicentet@iesreyescatolicos.com', 'AGRARIAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P007', 'Carlos Yera Solana', 'cayeras@iesreyescatolicos.com', 'AGRARIAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P008', 'M¬ Pilar Longas AcÝn', 'mplongasa@iesreyescatolicos.com', 'ARTES PL┴STICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P009', 'Laura Soriano Marco', 'lasorianom@iesreyescatolicos.com', 'ARTES PL┴STICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P010', 'Francisco Elizalde Lasheras', 'frelizaldel@iesreyescatolicos.com', 'BIOLOG═A Y GEOLOG═A', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P011', 'Javier Gutierrez Fernßndez', 'jagutierrezf@iesreyescatolicos.com', 'BIOLOG═A Y GEOLOG═A', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P012', 'Teresa NaudÝn Ayesa', 'tenaudina@iesreyescatolicos.com', 'BIOLOG═A Y GEOLOG═A', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P013', 'Marisa Ruiz Asensio', 'maruiza@iesreyescatolicos.com', 'BIOLOG═A Y GEOLOG═A', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P014', 'Irene Villa Orduna', 'irvillao@iesreyescatolicos.com', 'BIOLOG═A Y GEOLOG═A', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P015', 'Sandra Villa Navarro', 'savillan@iesreyescatolicos.com', 'ECONOM═A', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P016', 'Antonio Gallego Hernßndez', 'angallegoh@iesreyescatolicos.com', 'ECONOM═A', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P017', 'Gonzalo MondÚjar MartÝn', 'gomondejarm@iesreyescatolicos.com', 'EDUCACIËN F═SICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P018', 'David Boudet Azcßrate', 'daboudeta@iesreyescatolicos.com', 'EDUCACIËN F═SICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P019', 'Miguel ┴ngel Moreno NavascuÚs', 'mamorenon@iesreyescatolicos.com', 'EDUCACIËN F═SICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P020', 'Tomßs Puente GimÚnez', 'topuenteg@iesreyescatolicos.com', 'EDUCACIËN F═SICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P021', 'Ëscar Rodrigo Murillo', 'osrodrigom@iesreyescatolicos.com', 'EDUCACIËN F═SICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P022', 'Pablo BenedÚ J·lvez', 'pabenedej@iesreyescatolicos.com', 'EDUCACIËN F═SICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P023', 'Anabel MartÝnez Hernßndez', 'aimartinezh@iesreyescatolicos.com', 'FILOSOF═A', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P024', 'M¬ del Carmen Beltrßn Senao', 'mcbeltrans@iesreyescatolicos.com', 'FILOSOF═A', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P025', 'Julia Sabalza Monta±Ús', 'jusabalzam@iesreyescatolicos.com', 'FOL', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P026', 'Ana Millana Fa±anßs', 'anmillanaf@iesreyescatolicos.com', 'FRANC╔S', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P027', 'Sara Fuertes Soler', 'safuertess@iesreyescatolicos.com', 'FRANC╔S', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P028', 'MarÝa Gßllego Blasco', 'magallegob@iesreyescatolicos.com', 'FRANC╔S', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P029', 'Jes·s Marco Conde', 'jemarcoc@iesreyescatolicos.com', 'FRANC╔S', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P030', 'AndrÚs Membrado Royo', 'anmembrador@iesreyescatolicos.com', 'F═SICA Y QU═MICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P031', 'Laura Blas Aguerri', 'lablasa@iesreyescatolicos.com', 'F═SICA Y QU═MICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P032', 'Raquel Sagrario Sanz Lacosta', 'rssanzl@iesreyescatolicos.com', 'F═SICA Y QU═MICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P033', 'Antonio Lacosta Arag³Ús', 'ajlacostaa@iesreyescatolicos.com', 'GEOGRAF═A E HISTORIA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P034', 'Silvia Esca±uela Barradas', 'siescanuelab@iesreyescatolicos.com', 'GEOGRAF═A E HISTORIA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P035', 'Jaime Nu±o MartÝnez', 'janunom@iesreyescatolicos.com', 'GEOGRAF═A E HISTORIA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P036', 'Paloma Prßdanos Herrera', 'papradanosh@iesreyescatolicos.com', 'GEOGRAF═A E HISTORIA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P037', 'Diana Sancho Mal¾n', 'disanchom@iesreyescatolicos.com', 'GEOGRAF═A E HISTORIA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P038', 'Marina Senero Sauras', 'maseneros@iesreyescatolicos.com', 'INGL╔S', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P039', 'InÚs Pilar GimÚnez Urdßniz', 'ipgimenezu@iesreyescatolicos.com', 'INGL╔S', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P040', 'Silvia Guajardo Arag³Ús', 'siguajardoa@iesreyescatolicos.com', 'INGL╔S', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P041', 'Eva Luna Cardiel', 'evlunac@iesreyescatolicos.com', 'INGL╔S', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P042', 'Silvia Ma±ero Hernßndez', 'simaneroh@iesreyescatolicos.com', 'INGL╔S', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P043', 'Virginia Monforte Romßn', 'vimonforter@iesreyescatolicos.com', 'INGL╔S', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P044', 'Patricia Ponce PÚrez', 'paponcep@iesreyescatolicos.com', 'INGL╔S', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P045', 'Adriana Potrony Ciudad', 'adpotronyc@iesreyescatolicos.com', 'INGL╔S', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P046', 'Antonio Royo', 'anroyol@iesreyescatolicos.com', 'LAT═N Y GRIEGO', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P047', 'Vanesa Cueto Vi±au', 'vacuetov@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P048', 'Patxi AbadÝa ┴lvarez', 'paabadiaa@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P049', 'Tatiana Eusebio Ruiz Esquide', 'taeusebior@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P050', 'Sara Jaso PÚrez', 'sajasop@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P051', 'Dario Navarro Peguero', 'danavarrop@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P052', 'Javier Maldonado Fernßndez', 'jamaldonadof@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P053', 'M¬ JosÚ Miranda Romero', 'mjmirandar@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P054', 'Daniel Rodriguez Anaya', 'darodrigueza@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P055', 'MarÝa Rubio Torres', 'marubiot@iesreyescatolicos.com', 'LENGUA Y LITERATURA CASTELLANA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P056', 'Ana BelÚn Caraballo', 'abcaraballot@iesreyescatolicos.com', 'MATEM┴TICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P057', 'Primitiva Alcus¾n Puyuelo', 'pralcusonp@iesreyescatolicos.com', 'MATEM┴TICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P058', 'Francisco Javier GarcÝa Pardos', 'fjgarciap@iesreyescatolicos.com', 'MATEM┴TICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P059', '┴ngel Gumiel Correo', 'angumielc@iesreyescatolicos.com', 'MATEM┴TICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P060', 'JosÚ MarÝa Lorenzo MartÝnez', 'jmlorenzom@iesreyescatolicos.com', 'MATEM┴TICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P061', 'Ana Palma Cobo', 'anpalmac@iesreyescatolicos.com', 'MATEM┴TICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P062', 'Paula Villuendas Calvete', 'pavilluendasc@iesreyescatolicos.com', 'MATEM┴TICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P063', 'JosÚ MarÝa Moreno Loscertales', 'jmmorenol@iesreyescatolicos.com', 'MATEM┴TICAS', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P064', 'M¬ Esther Arilla Luna', 'mearillal@iesreyescatolicos.com', 'M┌SICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P065', 'Daniel GimÚnez PÚrez', 'dagimenezp@iesreyescatolicos.com', 'M┌SICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P066', 'Idoia Mena Ederra', 'idmenae@iesreyescatolicos.com', 'M┌SICA', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P067', 'MarÝa RuÝz Chueca', 'maruizc@iesreyescatolicos.com', 'ORIENTACIËN', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P068', 'M¬ Cruz Aznßrez Maiza', 'mcaznarezm@iesreyescatolicos.com', 'ORIENTACIËN', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P069', 'Bego±a Monta±Ús Arag³Ús', 'bemontanesa@iesreyescatolicos.com', 'ORIENTACIËN', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P070', 'Rosana Valenzuela Fuertes', 'rnvalenzuelaf@iesreyescatolicos.com', 'ORIENTACIËN', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P071', 'VÝctor Pola Aznar', 'vmpolaa@iesreyescatolicos.com', 'RELIGIËN', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P072', 'Beatriz Izuel Monta±Ús', 'beizuelm@iesreyescatolicos.com', 'SERVICIOS A LA COMUNIDAD', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P073', 'MarÝa del Pilar Aparicio Aguerri', 'mpaparicioa@iesreyescatolicos.com', 'SERVICIOS A LA COMUNIDAD', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P074', 'Miriam Buj Ibß±ez', 'mibuji@iesreyescatolicos.com', 'SERVICIOS A LA COMUNIDAD', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P075', 'AgustÝn Burillo Tomßs', 'agburillot@iesreyescatolicos.com', 'SERVICIOS A LA COMUNIDAD', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P076', 'Diana Gracia Villarrolla', 'digraciav@iesreyescatolicos.com', 'SERVICIOS A LA COMUNIDAD', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P077', 'Macarena Santa-Maria Megia', 'masantamariam@iesreyescatolicos.com', 'SERVICIOS A LA COMUNIDAD', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P078', 'Alejandro Yeste Iglesias', 'alyestei@iesreyescatolicos.com', 'PROCEDIMIENTOS SANITARIOS Y ASISTENCIALES', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P079', 'Virginia Benavente Monguilod', 'vibenaventem@iesreyescatolicos.com', 'TECNOLOG═A', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P080', 'Ana MarÝa Sßnchez Jarque', 'amsanchezj@iesreyescatolicos.com', 'TECNOLOG═A', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P081', 'Carolina Romero BeguerÝa', 'caromerob@iesreyescatolicos.com', 'TECNOLOG═A', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P082', 'MarÝa JosÚ Ca±iz MartÝn', 'administracion@iesreyescatolicos.com', 'PERSONAL ADMINISTRACIËN', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P083', 'Conchi Melero AbadÝa', 'administracion2@iesreyescatolicos.com', 'PERSONAL ADMINISTRACIËN', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P084', 'Direcci¾n (Patxi AbadÝa)', 'direccion@iesreyescatolicos.com', 'EQUIPO DIRECTIVO', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P085', 'Jefatura de Estudios', 'jefatura@iesreyescatolicos.com', 'EQUIPO DIRECTIVO', 'Usuario', 1);
INSERT INTO "Profesores" (id, "nombre y apellidos", email, departamento, rol, horas_guardia) VALUES ('P086', 'SecretarÝa (Primitiva Alcus¾n)', 'secretaria@iesreyescatolicos.com', 'EQUIPO DIRECTIVO', 'Usuario', 1);
COMMIT;
